# Generated by Django 2.2.19 on 2023-07-02 14:43

import core.enums
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(help_text='Обязательно для заполнения. Максимум 32 букв.', max_length=32, validators=[core.validators.OneOfTwoValidator(field='Имя', first_regex='[^а-яёА-ЯЁ -]+', second_regex='[^a-zA-Z -]+')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(help_text='Обязательно для заполнения. Максимум 32 букв.', max_length=32, validators=[core.validators.OneOfTwoValidator(field='Фамилия', first_regex='[^а-яёА-ЯЁ -]+', second_regex='[^a-zA-Z -]+')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(help_text='Обязательно для заполнения. От 3 до 32 букв.', max_length=32, unique=True, validators=[core.validators.MinLenValidator(field='username', message='\n%s недостаточной длины.\n', min_len=core.enums.Limits(3)), core.validators.OneOfTwoValidator(field='username', first_regex='[^а-яёА-ЯЁ]+', second_regex='[^a-zA-Z]+')], verbose_name='Уникальный юзернейм'),
        ),
    ]
